/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.celulao.gui;

import br.com.celulao.bean.Cliente;
import br.com.celulao.bean.OrdemServicoBean;
import br.com.celulao.gui.utils.Alert;
import br.com.celulao.gui.utils.ComponentBehavior;
import br.com.celulao.service.OrdemServicoService;
import java.awt.Dimension;
import java.awt.Toolkit;
/**
 *
 * @author SYSTEM
 */
public class HomeOrdemServico extends javax.swing.JDialog {
    Cliente mainCliente;
    OrdemServicoBean mainOrdemServico;
    
    /**
     * Creates new form HomeOrdemServico
     */
    public HomeOrdemServico(Cliente cliente, OrdemServicoBean selectedCodOrdemServico) {
        this.mainCliente = cliente;
        this.mainOrdemServico = selectedCodOrdemServico;
        
        initComponents();
        setModal(true);
        
        if(selectedCodOrdemServico==null) 
            prepFieldsNovaOrdemServico();
        else 
            prepFieldsOrdemServicoEncontrada();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSair = new javax.swing.JButton();
        panelDadosOS = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMarcaCelular = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPartesEntregues = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        txtModeloCelular = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtRelatoCliente = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        btnRegistrarDadosOS = new javax.swing.JButton();
        AbasTecnicoAtendente = new javax.swing.JTabbedPane();
        panelRelatoTecnico = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtRelatoTecnico = new javax.swing.JTextArea();
        btnRegistrarRelatoTecnico = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblServicoPecasTecnico = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtDescricaoItem = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtQuantidadeItemServico = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtValorItemServico = new javax.swing.JTextField();
        btnAdicionarItemServico = new javax.swing.JButton();
        panelRelatoAtendente = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtRelatoAtendente = new javax.swing.JTextArea();
        btnRegistrarRelatoAtendente = new javax.swing.JButton();
        panelOrcamento = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtValorTotalOrcamento = new javax.swing.JTextField();
        btnAprovarOrcamento = new javax.swing.JButton();
        btnReprovarOrcamento = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnExecutarServico = new javax.swing.JButton();
        btnCobrarDevolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        panelDadosOS.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados da OS"));

        jLabel1.setText("Marca:");

        jLabel2.setText("Partes entregues:");

        txtPartesEntregues.setColumns(20);
        txtPartesEntregues.setRows(5);
        jScrollPane1.setViewportView(txtPartesEntregues);

        jLabel3.setText("Modelo:");

        txtModeloCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModeloCelularActionPerformed(evt);
            }
        });

        txtRelatoCliente.setColumns(20);
        txtRelatoCliente.setRows(5);
        jScrollPane2.setViewportView(txtRelatoCliente);

        jLabel4.setText("Relato do cliente:");

        btnRegistrarDadosOS.setText("Registrar");
        btnRegistrarDadosOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarDadosOSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDadosOSLayout = new javax.swing.GroupLayout(panelDadosOS);
        panelDadosOS.setLayout(panelDadosOSLayout);
        panelDadosOSLayout.setHorizontalGroup(
            panelDadosOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDadosOSLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDadosOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDadosOSLayout.createSequentialGroup()
                        .addGroup(panelDadosOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelDadosOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                            .addComponent(txtMarcaCelular))
                        .addGap(23, 23, 23)
                        .addGroup(panelDadosOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDadosOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(txtModeloCelular)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDadosOSLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRegistrarDadosOS)))
                .addContainerGap())
        );
        panelDadosOSLayout.setVerticalGroup(
            panelDadosOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDadosOSLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDadosOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMarcaCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtModeloCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDadosOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(btnRegistrarDadosOS))
        );

        AbasTecnicoAtendente.setToolTipText("");
        AbasTecnicoAtendente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        panelRelatoTecnico.setBorder(javax.swing.BorderFactory.createTitledBorder("Relato do técnico"));

        txtRelatoTecnico.setColumns(20);
        txtRelatoTecnico.setRows(5);
        jScrollPane4.setViewportView(txtRelatoTecnico);

        btnRegistrarRelatoTecnico.setText("Registrar");

        tblServicoPecasTecnico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descricao Item", "Quantidade", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tblServicoPecasTecnico);

        jLabel5.setText("Descricao item:");

        jLabel6.setText("Quantidade:");

        jLabel7.setText("Valor:");

        btnAdicionarItemServico.setText("Adicionar");

        javax.swing.GroupLayout panelRelatoTecnicoLayout = new javax.swing.GroupLayout(panelRelatoTecnico);
        panelRelatoTecnico.setLayout(panelRelatoTecnicoLayout);
        panelRelatoTecnicoLayout.setHorizontalGroup(
            panelRelatoTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRelatoTecnicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRelatoTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRelatoTecnicoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRegistrarRelatoTecnico))
                    .addGroup(panelRelatoTecnicoLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelRelatoTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelRelatoTecnicoLayout.createSequentialGroup()
                                .addGroup(panelRelatoTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelRelatoTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panelRelatoTecnicoLayout.createSequentialGroup()
                                        .addComponent(txtQuantidadeItemServico, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtValorItemServico))
                                    .addComponent(txtDescricaoItem, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnAdicionarItemServico))
                        .addGap(0, 83, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelRelatoTecnicoLayout.setVerticalGroup(
            panelRelatoTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRelatoTecnicoLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegistrarRelatoTecnico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(panelRelatoTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRelatoTecnicoLayout.createSequentialGroup()
                        .addGroup(panelRelatoTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtDescricaoItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelRelatoTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtQuantidadeItemServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(txtValorItemServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAdicionarItemServico))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        AbasTecnicoAtendente.addTab("Técnico", panelRelatoTecnico);

        panelRelatoAtendente.setBorder(javax.swing.BorderFactory.createTitledBorder("Relato do atendente"));

        txtRelatoAtendente.setColumns(20);
        txtRelatoAtendente.setRows(5);
        jScrollPane3.setViewportView(txtRelatoAtendente);

        btnRegistrarRelatoAtendente.setText("Registrar");

        javax.swing.GroupLayout panelRelatoAtendenteLayout = new javax.swing.GroupLayout(panelRelatoAtendente);
        panelRelatoAtendente.setLayout(panelRelatoAtendenteLayout);
        panelRelatoAtendenteLayout.setHorizontalGroup(
            panelRelatoAtendenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRelatoAtendenteLayout.createSequentialGroup()
                .addGroup(panelRelatoAtendenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRelatoAtendenteLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRegistrarRelatoAtendente))
                    .addGroup(panelRelatoAtendenteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelRelatoAtendenteLayout.setVerticalGroup(
            panelRelatoAtendenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRelatoAtendenteLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegistrarRelatoAtendente)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        AbasTecnicoAtendente.addTab("Atendente", panelRelatoAtendente);

        jLabel8.setText("Valor total:");

        btnAprovarOrcamento.setText("Aprovar");
        btnAprovarOrcamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAprovarOrcamentoActionPerformed(evt);
            }
        });

        btnReprovarOrcamento.setText("Reprovar");

        javax.swing.GroupLayout panelOrcamentoLayout = new javax.swing.GroupLayout(panelOrcamento);
        panelOrcamento.setLayout(panelOrcamentoLayout);
        panelOrcamentoLayout.setHorizontalGroup(
            panelOrcamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOrcamentoLayout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addGroup(panelOrcamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelOrcamentoLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(btnAprovarOrcamento, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnReprovarOrcamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelOrcamentoLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtValorTotalOrcamento, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(240, Short.MAX_VALUE))
        );
        panelOrcamentoLayout.setVerticalGroup(
            panelOrcamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOrcamentoLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(panelOrcamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtValorTotalOrcamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelOrcamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAprovarOrcamento)
                    .addComponent(btnReprovarOrcamento))
                .addContainerGap(170, Short.MAX_VALUE))
        );

        AbasTecnicoAtendente.addTab("Orçamento", panelOrcamento);

        btnExecutarServico.setText("Executar serviço");

        btnCobrarDevolver.setText("Cobrar e devolver");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(237, Short.MAX_VALUE)
                .addComponent(btnExecutarServico)
                .addGap(18, 18, 18)
                .addComponent(btnCobrarDevolver)
                .addGap(231, 231, 231))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExecutarServico)
                    .addComponent(btnCobrarDevolver))
                .addContainerGap(160, Short.MAX_VALUE))
        );

        AbasTecnicoAtendente.addTab("Serviço", jPanel1);

        AbasTecnicoAtendente.setSelectedIndex(1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AbasTecnicoAtendente)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelDadosOS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDadosOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AbasTecnicoAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(btnSair)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        onCancel();
    }//GEN-LAST:event_btnSairActionPerformed

    private void txtModeloCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModeloCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModeloCelularActionPerformed

    private void btnAprovarOrcamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAprovarOrcamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAprovarOrcamentoActionPerformed

    private void btnRegistrarDadosOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarDadosOSActionPerformed
        // TODO add your handling code here:
        if(mainOrdemServico==null)
            criarNovaOrdemServico();
        else
            registraRelatoCliente();
    }//GEN-LAST:event_btnRegistrarDadosOSActionPerformed

    private void onCancel() {
        // add your code here if necessary
        dispose();
    }

    private void criarNovaOrdemServico() {
        try {
            OrdemServicoBean newOS = OrdemServicoService.createOrdemServicoByCliente(
                    mainCliente,
                    txtMarcaCelular.getText(),
                    txtModeloCelular.getText(),
                    txtPartesEntregues.getText());
            mainOrdemServico = newOS;
            prepFieldsOrdemServicoEncontrada();
        } catch (Exception ex) {
            ex.printStackTrace();
            Alert.showAlertOnField("Dados incorretos da OS. \n Exception:" + ex.getMessage());
        }
    }
    
    private void registraRelatoCliente() {
        try {
            
        } catch (Exception ex) {
            ex.printStackTrace();
            Alert.showAlertOnField("Não foi possível atualizar o relato do cliente. \n Exception:" + ex.getMessage());
        }
    }
    
    private void prepFieldsNovaOrdemServico() {
        // add your code here if necessary
        AbasTecnicoAtendente.setVisible(false);
    }
    
    private void prepFieldsOrdemServicoEncontrada() {
        // add your code here if necessary
        AbasTecnicoAtendente.setVisible(true);
        ComponentBehavior.completeAndEnable(txtMarcaCelular,mainOrdemServico.getCelularMarca(),false);
        ComponentBehavior.completeAndEnable(txtModeloCelular,mainOrdemServico.getCelularModelo(),false);
        ComponentBehavior.completeAndEnable(txtPartesEntregues,mainOrdemServico.getCelularPartesEntregues(),false);
        ComponentBehavior.completeAndEnable(txtRelatoCliente,"");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void run(Cliente cliente) {
        run(cliente,null);
    }
    
    public static void run(Cliente cliente, OrdemServicoBean selectedCodOrdemServico) {
        HomeOrdemServico dialog = new HomeOrdemServico(cliente, selectedCodOrdemServico);
        
        if(cliente!=null && selectedCodOrdemServico!=null){
            dialog.setTitle(
                "Ordem de Serviço: " + selectedCodOrdemServico.getCodOrdem() +
                        " - Cliente: " + cliente.getNomeReferencia() );            
        }
        else if(cliente!=null){
            dialog.setTitle(
                "Nova ordem de Serviço - Cliente: " 
                        + cliente.getNomeReferencia() );
        }
        
        final Toolkit toolkit = Toolkit.getDefaultToolkit().getDefaultToolkit();
        final Dimension screenSize = toolkit.getScreenSize();
        final int x = (screenSize.width - dialog.getWidth()) / 2;
        final int y = (screenSize.height - dialog.getHeight()) / 2;
        dialog.setLocation(x, y);
    
        dialog.setVisible(true);
        dialog.requestFocusInWindow();
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane AbasTecnicoAtendente;
    private javax.swing.JButton btnAdicionarItemServico;
    private javax.swing.JButton btnAprovarOrcamento;
    private javax.swing.JButton btnCobrarDevolver;
    private javax.swing.JButton btnExecutarServico;
    private javax.swing.JButton btnRegistrarDadosOS;
    private javax.swing.JButton btnRegistrarRelatoAtendente;
    private javax.swing.JButton btnRegistrarRelatoTecnico;
    private javax.swing.JButton btnReprovarOrcamento;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPanel panelDadosOS;
    private javax.swing.JPanel panelOrcamento;
    private javax.swing.JPanel panelRelatoAtendente;
    private javax.swing.JPanel panelRelatoTecnico;
    private javax.swing.JTable tblServicoPecasTecnico;
    private javax.swing.JTextField txtDescricaoItem;
    private javax.swing.JTextField txtMarcaCelular;
    private javax.swing.JTextField txtModeloCelular;
    private javax.swing.JTextArea txtPartesEntregues;
    private javax.swing.JTextField txtQuantidadeItemServico;
    private javax.swing.JTextArea txtRelatoAtendente;
    private javax.swing.JTextArea txtRelatoCliente;
    private javax.swing.JTextArea txtRelatoTecnico;
    private javax.swing.JTextField txtValorItemServico;
    private javax.swing.JTextField txtValorTotalOrcamento;
    // End of variables declaration//GEN-END:variables
}
